### ISSUE TITLE
Bump multicast-dns dependency

### ISSUE THREAD

**Issue by athal7** [homebridge/bonjour#11]
<img width="839" alt="Screen Shot 2021-08-31 at 10 19 48 AM" src="https://user-images.githubusercontent.com/467872/131519591-3c705cd3-284e-4d7e-9151-c51dc8c2e3dc.png">

multicast-dns v7.2.3 upgrades the dns-packet dependency to resolve this concern

**Comment by Supereg** [comment]
bonjour-hap v3.6.3 was pushed. Thanks for pointing this out.

**Comment by athal7** [comment]
@Supereg thanks for the fast response! Do you know if I should create issues on the other upstream projects (hap-nodejs, Homebridge) or if those will update to this new version via other means?
