### ISSUE TITLE
Fix MDNS Announcements

### ISSUE THREAD

**Issue by pwinkeler** [homebridge/bonjour#5]
To be compliant, the A and AAAA records (of the target of an announcement) should be published das "additional" records, not as answers

**Comment by Supereg** [comment]
Do you mean when we respond to a query or when we announce a new service to the world?
Could you provide the reference in the RFC?

**Comment by Supereg** [comment]
Thanks for your issue. The bonjour library is about to be replaced by new [ciao](https://github.com/homebridge/ciao) library (which is basically a rewrite). I'm not sure what exactly you wanted to point out with your issue, though ciao strongly follows the RFC, thus the issue is closed.
